### ISSUE TITLE
404 site not found when trying to register

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-sherlock#1]
on https://craftsherlock.com/register

We are using this url: `https://alaincoussens.com/`

**Comment by putyourlightson** [comment]
The https://craftsherlock.com web app only works with Sherlock v1 for Craft 2. Since the web app has been used by only a handful of people, we plan on discontinuing it in the near future.

**Comment by thaoms** [comment]
Ok, thank you for your reply!
