### ISSUE TITLE
Trying to get property 'username' of non-object

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#10]
Probably something obvious I'm doing wrong, but when running the curl command I get the above error?

**Comment by putyourlightson** [comment]
Is the error appearing in the control panel? Any more details if you enable `devMode`?

**Comment by sunscreem** [comment]
Hi @putyourlightson .. Its coming up on the stack trace on command line when I run the curl command (without the compressed and silent options) with dev mode on.

**Comment by putyourlightson** [comment]
Ah ok, found the issue and fixed in https://github.com/putyourlightson/craft-sherlock/commit/c2e539bc98223eaa12d6e8f9e5dc0d14a97926c7, thanks!

**Comment by sunscreem** [comment]
@putyourlightson all working now. Thank you.
