### ISSUE TITLE
[FR] Allow wildcards on admin ip address restrictions

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#11]
We would like to be able to restrict access to a clients admin via a pool of IP addresses. 

Could this be implemented?

**Comment by putyourlightson** [comment]
By a pool, do you mean a range of IP addresses, for example `213.147.166.92-213.147.166.100`? You can currently restrict to as many single IP addresses as you want by placing one per line.

**Comment by sunscreem** [comment]
Yeah - that's right. Probably more like `213.147.*` would be my preferred format.

**Comment by putyourlightson** [comment]
Just a quick update that we are planning on adding this to the plugin this week.

**Comment by sunscreem** [comment]
Brilliant news. Thanks.

**Comment by putyourlightson** [comment]
Released this in version 2.2.0. You can now use the `*` and `?` wildcards.
