### ISSUE TITLE
Postgres - Error Saving Scans

### ISSUE THREAD

**Issue by andrew-kaslick** [putyourlightson/craft-sherlock#12]
### Describe the bug
When using Postgres, attempting to run a scan results in the following error

> Exception (Integrity constraint violation) 'yii\db\IntegrityException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint
> DETAIL:  Failing row contains (null, f, f, t, {"fail":{"httpsControlPanel":""},"warning":{"httpsFrontEnd":"","..., 2020-03-25 16:20:40, 2020-03-25 16:20:40, 96401126-f3d9-4187-bb6b-42479ff32629).

It looks like explicitly setting the `id` to null [when saving a scan](https://github.com/putyourlightson/craft-sherlock/blob/5d3e32e85a94559515ac5b9e912024a5b47e582c/src/services/SherlockService.php#L216) causes this error to be thrown using Postgres. As a test, adding `unset($scanRecord->id);` before calling the save() method did result in scans being saved without the error. 

### Versions
- Plugin version: 2.2.0
- Craft version: 3.3.20.1
- PostgreSQL 11.7

**Comment by bencroker** [comment]
Thanks for the bug report, fixed in https://github.com/putyourlightson/craft-sherlock/commit/590711503a3f768ca258f78eec4144ee4c440d90 and released in 2.2.1.
