### ISSUE TITLE
Scans no longer running.

### ISSUE THREAD

**Issue by billythekid** [putyourlightson/craft-sherlock#13]
### Describe the bug
Running a scan gives me an internal server error, which I've narrowed to ` yii\base\ErrorException · Invalid argument supplied for foreach()` on line 209 of SherlockService.php

### To reproduce
Steps to reproduce the behaviour:
1. Go to [admin]/sherlock
2. Click on Scan now
3. See error message Internal Server Error

### Expected behaviour
The scan runs and displays the results.

### Versions
- Plugin version: 2.2.1
- Craft version: 3.4.11 (This stopped working the day I upgraded Craft from 3.2 to 3.4.8)
- PHP version: 7.3.6

**Comment by bencroker** [comment]
Thanks for the bug report, fixed in version 2.2.2.

**Comment by billythekid** [comment]
Cheers @bencroker. Fix applied and scans running fine again!
