### ISSUE TITLE
Can't get sherlock to run!

### ISSUE THREAD

**Issue by mwakeham** [putyourlightson/craft-sherlock#14]
Hi, I'm concerned being a craft newbie that i'm being totally stupid here. I've setup a new site publically but when I access sherlock it just sits there spinning on "Running a scan" and i get nothing back. I did notice that in the developer tools I get the error below and have ensured the site is on and i've reinstalled about 5 times so far! I'm puzzled.

Failed to load resource: the server responded with a status of 500 (). /index.php?p=admin/actions/sherlock/scans/run-scan-ajax:1 

Thank you for your help in advance.

**Comment by bencroker** [comment]
Can you check what the response error message is? You should be able to see this in the Network tab of the developer tools. If the error message is generic then either enable [Dev Mode](https://craftcms.com/knowledge-base/what-dev-mode-does) or check the `web.log` file.

**Comment by mwakeham** [comment]
Hi, I can't see anything more. i've included the web.log incase you can spot anything.



SME IT (UK) LTD
Matthew Wakeham
SME IT (UK) LTD
P: 01708 547000 | M: 07966 572884
E: mwakeham@smeit.co.uk | W: www.smeit.co.uk
A: Elms House, Church Road, Harold Wood, Essex, RM3 0JU
Protecting our Customers
Consider the environment. Do you really need to print this email?
________________________________

**Comment by bencroker** [comment]
No files came through, maybe try attaching in the github issue itself?

**Comment by mwakeham** [comment]
[web.log](https://github.com/putyourlightson/craft-sherlock/files/4553843/web.log)
Hi Ben, Please find attached the web.log. Thanks you in advance

**Comment by mwakeham** [comment]
Bugger, Just done it via github. Thanks Ben


SME IT (UK) LTD
Matthew Wakeham
SME IT (UK) LTD
P: 01708 547000 | M: 07966 572884
E: mwakeham@smeit.co.uk | W: www.smeit.co.uk
A: Elms House, Church Road, Harold Wood, Essex, RM3 0JU
Protecting our Customers
Consider the environment. Do you really need to print this email?
________________________________

**Comment by bencroker** [comment]
This error appears in the log file, so I'm guessing the system is switched off.
```
HttpException: unable to connect to https://www.smeit.com/. Please ensure that the site is reachable and that the system is turned on.
```

**Comment by mwakeham** [comment]
Ben, I’m so sorry for wasting your time. I swear last night I had turned the site on! Maybe I’m just going made but I do leave it off whilst developing/learning.


SME IT (UK) LTD
Matthew Wakeham
SME IT (UK) LTD
P: 01708 547000 | M: 07966 572884
E: mwakeham@smeit.co.uk | W: www.smeit.co.uk
A: Elms House, Church Road, Harold Wood, Essex, RM3 0JU
Protecting our Customers
Consider the environment. Do you really need to print this email?

On 29 Apr 2020, at 20:03, Ben Croker <notifications@github.com> wrote:

﻿

This error appears in the log file, so I'm guessing the system is switched off.

HttpException: unable to connect to https://www.smeit.com/. Please ensure that the site is reachable and that the system is turned on.

**Comment by bencroker** [comment]
That's ok Matthew, is it working for you now?

**Comment by mwakeham** [comment]
Yes all seems great. It must be this lock down sending me crazy!! Really sorry for wasting your time.


SME IT (UK) LTD
Matthew Wakeham
SME IT (UK) LTD
P: 01708 547000 | M: 07966 572884
E: mwakeham@smeit.co.uk | W: www.smeit.co.uk
A: Elms House, Church Road, Harold Wood, Essex, RM3 0JU
Protecting our Customers
Consider the environment. Do you really need to print this email?
________________________________
