### ISSUE TITLE
Testing running for 5 hours

### ISSUE THREAD

**Issue by senpuukyakuu** [putyourlightson/craft-sherlock#15]
### Question
Hi Guys, 
I've been testing the plugin for a customer site and it's been running for 6 hours straight, how long does the test should take?
I'm not sure if it's normal, and since there's no progress bar I'm a bit in the dark
### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
It should only take a few seconds, can you please check for errors in the browser network tab or in the logs? 

Is the site publicly accessible?

**Comment by senpuukyakuu** [comment]
I was trying to run the scan with the site offline, because of security
reasons.
We've been hacked twice this weekend and I wanted to make a scan before
doing anything else.
The Problem is, I can't stop the process now and it keeps working and doing
nothing.
Thanks ,
D,

**Comment by senpuukyakuu** [comment]
Even with the site online I keep getting a 500 error on
index.php?p=admin/actions/sherlock/scans/run-scan-ajax

**Comment by putyourlightson** [comment]
Can you check for errors in the Craft logs?

**Comment by bencroker** [comment]
Can you check for errors in the Craft logs?

**Comment by senpuukyakuu** [comment]
yii\web\HttpException: unable to connect to https://www.youngvoices.co.uk/.
Please ensure that the site is reachable and that the system is turned on.
in /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/putyourlightson/craft-sherlock/src/services/TestsService.php:152
Stack trace:
#0 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/putyourlightson/craft-sherlock/src/services/SherlockService.php(149):
putyourlightson\sherlock\services\TestsService->runTest('criticalCraftUp...')
#1 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/putyourlightson/craft-sherlock/src/controllers/ScansController.php(128):
putyourlightson\sherlock\services\SherlockService->runScan()
#2 [internal function]:
putyourlightson\sherlock\controllers\ScansController->actionRunScanAjax()
#3 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)
#4 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/yiisoft/yii2/base/Controller.php(157):
yii\base\InlineAction->runWithParams(Array)
#5 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/craftcms/cms/src/web/Controller.php(187):
yii\base\Controller->runAction('run-scan-ajax', Array)
#6 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/yiisoft/yii2/base/Module.php(528):
craft\web\Controller->runAction('run-scan-ajax', Array)
#7 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/craftcms/cms/src/web/Application.php(299):
yii\base\Module->runAction('sherlock/scans/...', Array)
#8 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/craftcms/cms/src/web/Application.php(565):
craft\web\Application->runAction('sherlock/scans/...', Array)
#9 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/craftcms/cms/src/web/Application.php(278):
craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/vendor/yiisoft/yii2/base/Application.php(386):
craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /chroot/home/youngvoi/
youngvoices.co.uk/youngvoices_production/web/index.php(21):
yii\base\Application->run()
#12 /chroot/home/youngvoi/youngvoices.co.uk/html/index.php(19):
require_once('/chroot/home/yo...')
#13 {main}


The site is up and running, I thought Cloudflare might be interfering so I
turned it off.
On the testing environment works ok.
Not sure what is going on.
D,

**Comment by senpuukyakuu** [comment]
Ok, no worries.
It was cloudflare, just so you know for the next time.
The delay Cloudflare creates to avoid DDoS interferes with the scan.
Thanks,
D,

**Comment by bencroker** [comment]
Ok, glad to hear you figured it out!
