### ISSUE TITLE
X-XSS-Protection Header is set correctly, but Sherlock reports its not.

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#16]
### Describe the bug

A picture says a thousand words:

![image](https://user-images.githubusercontent.com/7523595/87287936-9b9b5700-c4f2-11ea-9732-59c1eab76c0f.png)

But...

![image](https://user-images.githubusercontent.com/7523595/87288065-c1286080-c4f2-11ea-9ff1-f2e908f241c1.png)

(This is via https://securityheaders.com/)

### Versions
- Plugin version: 2.2.4
- Craft version: Craft Pro 3.4.27

**Comment by bencroker** [comment]
This should have been fixed in 2.2.4, can you please double check that you’re on that version?
https://github.com/putyourlightson/craft-sherlock/blob/develop/CHANGELOG.md#224---2020-07-02

**Comment by sunscreem** [comment]
![image](https://user-images.githubusercontent.com/7523595/87292327-8e816680-c4f8-11ea-8bf5-7124988ade64.png)

yeah - updated on Saturday @bencroker.

Just re-ran the scan too and still there.

**Comment by bencroker** [comment]
Thanks @sunscreem, fixed in https://github.com/putyourlightson/craft-sherlock/commit/58c8a663d4d892ba593a3d0fbcf19cc3a68dec8c for the next release.

**Comment by sunscreem** [comment]
@bencroker Any news on when this might be released?

**Comment by bencroker** [comment]
Just released in version 2.2.5.
