### ISSUE TITLE
Modified files

### ISSUE THREAD

**Issue by andrewfairlie** [putyourlightson/craft-sherlock#17]
### Describe the solution you would like
Theoretically a hacker could adjust files in the `vendor` folder and change Craft or a plugins code to do something unintended.

It would be great if Sherlock could compare the file system's hash with that packages hash. Could this bit be used...

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1772888/89196556-4955cf00-d5a2-11ea-8974-852a08ea0e68.png">

And flag it as a potential risk of manipulated code.

Extending this out to template files, custom plugins and modules with some way of the author providing an MD5 hash of what it _should_ be would also allow Sherlock to highlight potentially modified code (eg: JS injections in the layout file).

ExpressionEngine used to have a feature that alerted you when core files (index.php specifically) was changed. This suggestion is similar to that on a bigger scale.

**Comment by bencroker** [comment]
Thanks for the suggestion but monitoring the file system is not within the scope of the plugin. I'm aware that EE used to do this but whether it actually helps to mitigate hacks is very questionable.
