### ISSUE TITLE
Internal Server Errors

### ISSUE THREAD

**Issue by ScarIsbell** [putyourlightson/craft-sherlock#18]
### To reproduce
Steps to reproduce the behaviour:
1. Go to Sherlock main screen
2. Click on "Run Scan"
3. See error message "Internal Server Error - Server Error"

### Expected behaviour
I just installed Sherlock today and the first initial scan went just fine. Now I'm getting this vague Internal Server error. 

### Screenshots
https://www.thecarpetshoppe.com/assets/Screen-Shot-2020-08-03-at-3.13.44-PM.png

### Versions
- Plugin version: 2.2.4
- Craft version: 3.4.30

**Comment by bencroker** [comment]
While I agree that the error could be more descriptive, some errors don't provide more information unless the site has `devMode` enabled.

You should be able to find the specific error in the logs:
https://craftcms.com/knowledge-base/locating-error-logs-and-database-backups

**Comment by ScarIsbell** [comment]
Thanks Ben, 

It seems to be working as expected now.

**Comment by bencroker** [comment]
Great, glad to hear it!
