### ISSUE TITLE
Headers set correctly, but Sherlock reports they aren't

### ISSUE THREAD

**Issue by engram-design** [putyourlightson/craft-sherlock#19]
### Describe the bug
A bunch of header-related errors are reporting incorrectly.

Refer to https://securityheaders.com/ screenshot:

![Screen Shot 2020-10-19 at 1 01 25 pm](https://user-images.githubusercontent.com/1221575/96393603-57170a00-120b-11eb-8d83-88e09b0398a7.png)

And Sherlock's report:
![Screen Shot 2020-10-19 at 1 02 37 pm](https://user-images.githubusercontent.com/1221575/96393615-639b6280-120b-11eb-95b0-be3a2166c864.png)

What's pretty odd is that it's saying the front-end isn't on HTTPS - it very certainly is. We've got forced "www", but I've tried every possible combination and it redirects properly.

### Versions
- Plugin version: 2.2.5
- Craft version: 3.5.12.1

**Comment by bencroker** [comment]
When we discussed this last there was a server issue, was this resolved?

**Comment by engram-design** [comment]
Still working on it, but I believe a mis-configured SSL certificate might be the issue.
