### ISSUE TITLE
IP Restriction

### ISSUE THREAD

**Issue by aarmitage** [putyourlightson/craft-sherlock#2]
Hi Ben,

Just wondered if the IP restriction affects different user groups? We've added IP rules (client has 2 IP addresses) and our own IP. We can continue to access the site, but the client can't. I'm not sure if this is because we're admins, or whether it's because the IP locker excludes other user groups?

This is on the CP access only. Running Craft CMS 3.0.35.

**Comment by putyourlightson** [comment]
Hi Andrew. Logged in as an admin, you'll have access to the CP regardless of your IP address. Can you try accessing the CP as a user that is not an admin? That may help narrow the issue down. I'd also suggest double checking that the client's IP adresses are in the IP rules.

**Comment by aarmitage** [comment]
We've double checked the IP addresses which are correct, and can confirm it is a non-admin user who's unable to access the site. This is what they see.

![pastedimage](https://user-images.githubusercontent.com/1152884/50637442-f6dda800-0f51-11e9-9f85-32fbcd883374.png)

**Comment by putyourlightson** [comment]
Can you ensure that there is one IP address per line, no commas or trailing spaces. If the issue persists then you can PM me on slack.

**Comment by putyourlightson** [comment]
Fixed in version 2.0.2.
