### ISSUE TITLE
Sherlock reports that "Craft folders not located above the web root" but it is.

### ISSUE THREAD

**Issue by RyanRoberts** [putyourlightson/craft-sherlock#20]
### Describe the bug
As the title says, Sherlock reports "Craft folders not located above the web root" but it defo is.

### Expected behaviour
Confirmation that it's not above web root.

### Screenshots
Sherlock: https://cln.sh/VyUVuV
Website: https://cln.sh/vMud2q

### Versions
- Plugin version: 3.0.0
- Craft version: 3.5.18

**Comment by bencroker** [comment]
Have you defined the `@webroot` alias anywhere? I assume you're running the scan from the plugin page in the control panel (and not the console)?

**Comment by RyanRoberts** [comment]
Yeah it's in the control panel rather than console. I've not used @webroot anywhere.

**Comment by bencroker** [comment]
I've tried to reproduce this using a web root directory named `public` but the test passes. 

I added extra logging for that test. If you are able to install the following branch then it will log the value that is failing to `storage/logs/sherlock.log`.
https://github.com/putyourlightson/craft-sherlock/tree/test/webroot

**Comment by bencroker** [comment]
Any update on whether that provided any insight @RyanRoberts?

**Comment by RyanRoberts** [comment]
@bencroker Sorry for the delay, I'm unsure how to install via a different branch. Can you offer direction on that? Otherwise I'll see what I can do this evening. But thanks for getting back :)

**Comment by bencroker** [comment]
```
composer require putyourlightson/craft-sherlock:dev-test/webroot
```

**Comment by RyanRoberts** [comment]
I was missing the "dev-"! Thanks. I'll go test…

**Comment by RyanRoberts** [comment]
Right so this makes sense:
```
The `@webroot` alias was determined to be . 
```

The .env file has `WEB_ROOT_PATH` set to `"."` I can't remember the exact reason why it's that but it resolved a heap of other problems I was having, and this was the solution.

**Comment by bencroker** [comment]
Great, setting that properly will surely make your site more secure!
