### ISSUE TITLE
Getting a 500 in the dashboard

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#22]
### Describe the bug
Updated from version to to 3.1 and I'm getting a 500 in the dashboard.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Sherlock in the dashboard

### Screenshots
Here's what I'm seeing on BugSnag:

<details> 
  <summary>Full Stack Trace:</summary>

Twig\Error\RuntimeError
GET /jc/sherlock
An exception has been thrown during the rendering of a template ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause'
The SQL being executed was: SELECT *
FROM `sherlock`
WHERE (`siteId`=1) AND (id > 0)
ORDER BY `dateCreated` DESC").
Jan 30th, 2021, 14:20:17 GMT

STACKTRACE

Twig\Error\RuntimeError An exception has been thrown during the rendering of a template ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause'
The SQL being executed was: SELECT *
FROM `sherlock`
WHERE (`siteId`=1) AND (id > 0)
ORDER BY `dateCreated` DESC"). 
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/templates/index.html:48 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:495 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::block_main
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:314 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::block_body
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/44/4480f8fff5ce8a23384492b7d3e7d0fbcd353fed33db9ac852c11a10077d48ee.php:85 __TwigTemplate_f6fa64f911b32752788d8268d286c07beaca3a3f8eee25e7446464f8b9285415::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/5e/5e30347d5ff3df469fce5bedc8cd2a6838ea1b27cde77037406fb1e680a8a156.php:56 __TwigTemplate_2fc3dfc5ef06c237f3720d124854265926fa3a30a921ef12fa723e8796dcf9b7::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:156 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/49/49a0c9dd7ff2bbf86b11df7ebfb86aa171d121085d425af10ae73c8f568b2809.php:63 __TwigTemplate_130cc75e3f744057957af15c378692d36b4b05c780391d7b89d03a54bd17682d::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/2b/2bb60ae7b6236939a145aa14b443370e8f86c6afba8d269a756f89bf7dc76546.php:54 __TwigTemplate_e38918a7a304c6d2c76ae815c59e2d60a9ea6e90af9dc2ec2f5c38421acbdd43::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:390 Twig\Template::render
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/TemplateWrapper.php:45 Twig\TemplateWrapper::render
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Environment.php:318 Twig\Environment::render
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/View.php:389 craft\web\View::renderTemplate
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/View.php:450 craft\web\View::renderPageTemplate
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Controller.php:257 craft\web\Controller::renderTemplate
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/controllers/ScansController.php:58 putyourlightson\sherlock\controllers\ScansController::actionIndex
    [internal] call_user_func_array
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/InlineAction.php:57 yii\base\InlineAction::runWithParams
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Controller.php:181 yii\base\Controller::runAction
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Controller.php:190 craft\web\Controller::runAction
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Module.php:534 yii\base\Module::runAction
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Application.php:274 craft\web\Application::runAction
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/web/Application.php:104 yii\web\Application::handleRequest
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Application.php:259 craft\web\Application::handleRequest
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Application.php:392 yii\base\Application::run
    /home/forge/jc.tuckshop.design/web/index.php:23 [main]

Caused by: yii\db\Exception SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause'
The SQL being executed was: SELECT *
FROM `sherlock`
WHERE (`siteId`=1) AND (id > 0)
ORDER BY `dateCreated` DESC 
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Schema.php:678 yii\db\Schema::convertException
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:1304 yii\db\Command::internalExecute
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:1165 yii\db\Command::queryInternal
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:407 yii\db\Command::queryAll
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Query.php:248 yii\db\Query::all
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/ActiveQuery.php:133 yii\db\ActiveQuery::all
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/services/ScansService.php:62 putyourlightson\sherlock\services\ScansService::getAllScans
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/variables/SherlockVariable.php:43 putyourlightson\sherlock\variables\SherlockVariable::getAllScans
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Extension/CoreExtension.php:1507 twig_get_attribute
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/helpers/Template.php:106 craft\helpers\Template::attribute
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/2b/2bb60ae7b6236939a145aa14b443370e8f86c6afba8d269a756f89bf7dc76546.php:102 __TwigTemplate_e38918a7a304c6d2c76ae815c59e2d60a9ea6e90af9dc2ec2f5c38421acbdd43::block_content
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:495 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::block_main
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:314 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::block_body
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/44/4480f8fff5ce8a23384492b7d3e7d0fbcd353fed33db9ac852c11a10077d48ee.php:85 __TwigTemplate_f6fa64f911b32752788d8268d286c07beaca3a3f8eee25e7446464f8b9285415::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/5e/5e30347d5ff3df469fce5bedc8cd2a6838ea1b27cde77037406fb1e680a8a156.php:56 __TwigTemplate_2fc3dfc5ef06c237f3720d124854265926fa3a30a921ef12fa723e8796dcf9b7::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:156 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/49/49a0c9dd7ff2bbf86b11df7ebfb86aa171d121085d425af10ae73c8f568b2809.php:63 __TwigTemplate_130cc75e3f744057957af15c378692d36b4b05c780391d7b89d03a54bd17682d::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/2b/2bb60ae7b6236939a145aa14b443370e8f86c6afba8d269a756f89bf7dc76546.php:54 __TwigTemplate_e38918a7a304c6d2c76ae815c59e2d60a9ea6e90af9dc2ec2f5c38421acbdd43::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:390 Twig\Template::render
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/TemplateWrapper.php:45 Twig\TemplateWrapper::render
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Environment.php:318 Twig\Environment::render
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/View.php:389 craft\web\View::renderTemplate
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/View.php:450 craft\web\View::renderPageTemplate
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Controller.php:257 craft\web\Controller::renderTemplate
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/controllers/ScansController.php:58 putyourlightson\sherlock\controllers\ScansController::actionIndex
    [internal] call_user_func_array
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/InlineAction.php:57 yii\base\InlineAction::runWithParams
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Controller.php:181 yii\base\Controller::runAction
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Controller.php:190 craft\web\Controller::runAction
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Module.php:534 yii\base\Module::runAction
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Application.php:274 craft\web\Application::runAction
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/web/Application.php:104 yii\web\Application::handleRequest
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Application.php:259 craft\web\Application::handleRequest
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Application.php:392 yii\base\Application::run
    /home/forge/jc.tuckshop.design/web/index.php:23 [main]

Caused by: PDOException SQLSTATE[42S22]: Column not found: 1054 Unknown column 'siteId' in 'where clause' 
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:1299 PDOStatement::execute
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:1299 yii\db\Command::internalExecute
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:1165 yii\db\Command::queryInternal
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Command.php:407 yii\db\Command::queryAll
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/Query.php:248 yii\db\Query::all
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/db/ActiveQuery.php:133 yii\db\ActiveQuery::all
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/services/ScansService.php:62 putyourlightson\sherlock\services\ScansService::getAllScans
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/variables/SherlockVariable.php:43 putyourlightson\sherlock\variables\SherlockVariable::getAllScans
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Extension/CoreExtension.php:1507 twig_get_attribute
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/helpers/Template.php:106 craft\helpers\Template::attribute
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/2b/2bb60ae7b6236939a145aa14b443370e8f86c6afba8d269a756f89bf7dc76546.php:102 __TwigTemplate_e38918a7a304c6d2c76ae815c59e2d60a9ea6e90af9dc2ec2f5c38421acbdd43::block_content
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:495 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::block_main
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:314 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::block_body
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:182 Twig\Template::displayBlock
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/44/4480f8fff5ce8a23384492b7d3e7d0fbcd353fed33db9ac852c11a10077d48ee.php:85 __TwigTemplate_f6fa64f911b32752788d8268d286c07beaca3a3f8eee25e7446464f8b9285415::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/5e/5e30347d5ff3df469fce5bedc8cd2a6838ea1b27cde77037406fb1e680a8a156.php:56 __TwigTemplate_2fc3dfc5ef06c237f3720d124854265926fa3a30a921ef12fa723e8796dcf9b7::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/e5/e57f6fc1bad2869d44f6c09a765d19c47c985c368a0440da5369b5bc9e83ff67.php:156 __TwigTemplate_a12ea67185ba92af6624c53a8322c3216f3e6a6de24b7e9ccf108912c44ae771::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/49/49a0c9dd7ff2bbf86b11df7ebfb86aa171d121085d425af10ae73c8f568b2809.php:63 __TwigTemplate_130cc75e3f744057957af15c378692d36b4b05c780391d7b89d03a54bd17682d::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/storage/runtime/compiled_templates/2b/2bb60ae7b6236939a145aa14b443370e8f86c6afba8d269a756f89bf7dc76546.php:54 __TwigTemplate_e38918a7a304c6d2c76ae815c59e2d60a9ea6e90af9dc2ec2f5c38421acbdd43::doDisplay
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:405 Twig\Template::displayWithErrorHandling
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:378 Twig\Template::display
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Template.php:390 Twig\Template::render
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/TemplateWrapper.php:45 Twig\TemplateWrapper::render
    /home/forge/jc.tuckshop.design/vendor/twig/twig/src/Environment.php:318 Twig\Environment::render
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/View.php:389 craft\web\View::renderTemplate
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/View.php:450 craft\web\View::renderPageTemplate
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Controller.php:257 craft\web\Controller::renderTemplate
    /home/forge/jc.tuckshop.design/vendor/putyourlightson/craft-sherlock/src/controllers/ScansController.php:58 putyourlightson\sherlock\controllers\ScansController::actionIndex
    [internal] call_user_func_array
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/InlineAction.php:57 yii\base\InlineAction::runWithParams
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Controller.php:181 yii\base\Controller::runAction
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Controller.php:190 craft\web\Controller::runAction
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Module.php:534 yii\base\Module::runAction
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Application.php:274 craft\web\Application::runAction
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/web/Application.php:104 yii\web\Application::handleRequest
    /home/forge/jc.tuckshop.design/vendor/craftcms/cms/src/web/Application.php:259 craft\web\Application::handleRequest
    /home/forge/jc.tuckshop.design/vendor/yiisoft/yii2/base/Application.php:392 yii\base\Application::run
    /home/forge/jc.tuckshop.design/web/index.php:23 [main]
    
</details>

### Versions
- Plugin version: 3.1.0
- Craft version: Craft Pro 3.6.2

**Comment by bencroker** [comment]
You didn't say what you updated from, but it looks like an update migration was not successfully run. Can you either run the command `php craft migrate/up --plugin=sherlock`, or uninstall and install the plugin fresh?

**Comment by sunscreem** [comment]
Hey @bencroker 

```
forge@TuckShop:~/jc.tuckshop.design$ ./craft migrate/up --plugin=sherlock
Yii Migration Tool (based on Yii v2.0.40)

No new migrations found. Your system is up-to-date.
```

No joy there.

Coming from Craft version `3.5.17.1`

Trying the uninstall, re-install worked ✅

**Comment by bencroker** [comment]
Updating Craft should not affect the plugin at all, it must not have been installed correctly the first time.
