### ISSUE TITLE
Scheduled scan failed

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#24]
### Describe the bug
The scheduled scan has a permissions issue following the upgrade to v3.

Bug details (via BugSnag)

```
yii\web\ForbiddenHttpException
GET /actions/sherlock/scans/run-scan
User is not permitted to perform this action
Feb 3rd, 2021, 08:00:03 **GMT**
```

### Versions
- Plugin version: 3.1.0
- Craft version: Craft Pro 3.6.2

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-sherlock/commit/5cbd88f8fe0b46bdb98f5f27d216f9062f38e392 and released in version 3.1.1.
