### ISSUE TITLE
Sherlock crashed our craft frontend and backend

### ISSUE THREAD

**Issue by ballmannweber** [putyourlightson/craft-sherlock#25]
we installed Sherlock and tried the report feature. 
after that we tried for several different header options seeing that some where to strict to load the needed scripts via cdn etc.
we tried to deactive the left switch without success and deleted the content of the line. since saving this state the neither the front- nor the backend is available: "protocol error"

how can I uninstall or deactivate sherlock via ssh?

**Comment by bencroker** [comment]
You can run the following commands to disable or uninstall the plugin.

```shell
php craft plugin/disable sherlock

php craft plugin/uninstall sherlock
```

If you can tell me what rules you set or how to replicate this then I'd be happy to help troubleshoot the issues.

**Comment by ballmannweber** [comment]
thank you, now the front- and backend are back and running!

I ran the Security Scan with the following results:
<img width="1380" alt="Bildschirmfoto 2021-02-10 um 11 39 30" src="https://user-images.githubusercontent.com/5177628/107499229-fe41f780-6b94-11eb-88ce-8307f1f62f93.png">

I tried several settings for the Content-Security-Policy via the Header Protection-settings-table and I think the last setting was…

`Content-Security-Policy: default-src 'self'; img-src *; script-src https://code.jquery.com https://unpkg.com https://www.googletagmanager.com;`

but I noticed every setting including this blocks many things in craft’s backend too so I wanted to disable these last settings by clicking the switch on the left side but it didn’t move. clicking the delete-x on the right side didn’t result in any action neither so I deleted "Content-Security-Policy" from the left side and "default-src 'self'; img-src *; script-src https://code.jquery.com https://unpkg.com https://www.googletagmanager.com;" from the right side of the table and clicked on "dashboard" to check if this was back (the CSP-settings also seem to block the widgets there).

after that the safari browser window was blank with an "protocoll error" and the cp as well as the front end were gone.

on a side note: the scan marked "Dynamic @web alias is used in volume base URL: Bilder" but I’ve set the @web alias in general with an alias…

`'aliases' => [
	'@web' => getenv('PRIMARY_SITE_URL'),`

to my env-file where it is resolved: 

`PRIMARY_SITE_URL=https://my.website.com`

isn’t that the right way?
I think I even used the official Craft manual as a guide for this.

regards
matthias

**Comment by bencroker** [comment]
Thanks, I'll look into the CSP issue and see if I can replicate locally. It should only affect the front-end site, not the control panel, so not sure why you couldn't login and change it.

> on a side note: the scan marked "Dynamic @web alias is used in volume base URL: Bilder" but I’ve set the @web alias in general with an alias…

What version of Sherlock and Craft are you running?

**Comment by ballmannweber** [comment]
I am running craft 3.6.4.1 and sherlock 3.1.1.

**Comment by bencroker** [comment]
I cannot replicate the dynamic `@web` alias test failing. Can you run another test from the control panel to be sure?

**Comment by ballmannweber** [comment]
I ran the test again and the result is pretty much the same: 

<img width="1388" alt="Bildschirmfoto 2021-02-10 um 19 55 15" src="https://user-images.githubusercontent.com/5177628/107557760-4cc5b500-6bda-11eb-821b-f4ce35bcc3f3.png">

**Comment by bencroker** [comment]
I can't replicate any of the issues you are having, maybe best to remove and reinstall the plugin to eliminate the risk of old or corrupt files.
