### ISSUE TITLE
Craft's CP Alerts Are Nuked

### ISSUE THREAD

**Issue by mattgrayisok** [putyourlightson/craft-sherlock#27]
### Describe the bug
Rather than appending additional alerts to Craft's CP Alerts event the plugin is nuking it, preventing Craft or any other plugins from displaying alerts in the CP. Greedy.

See here which should be performing an array_merge on any existing alerts rather than replacing them entirely:

https://github.com/putyourlightson/craft-sherlock/blob/675f1be6f21b22dc86586dcca3f5879a90bbf7ca/src/Sherlock.php#L215

### To reproduce
Steps to reproduce the behaviour:
1. Do something to trigger an alert in the Craft CP (bad license or something)
2. Have this plugin installed
3. See no alerts in the Craft CP

### Expected behaviour
Perform an array_merge on CP alerts in order to allow other plugins and Craft to display them too.

🍉

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-sherlock/commit/23f0237a062f7a17025fb076cf5bda3f82d234ef for the next release, thanks Matt!

**Comment by bencroker** [comment]
Released in 3.1.2.
