### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by InLoop-TOCA** [putyourlightson/craft-sherlock#3]
Hi,
is it possible to setup sherlock over HTTPS only to run the scan?

Since HTTP is blocked when i click on, 'run scan now' i'm getting error below for both sites:
Internal Server Error: unable to connect to http://www.example.com/. Please ensure that the site is reachable and that the system is turned on.

Please let me know if you need any information.

Regards,

Chan

**Comment by putyourlightson** [comment]
This seems to be an issue with the site not being turned on in Settings → General → System Status. Can you check if turning it on prevents the error message?

**Comment by InLoop-TOCA** [comment]
yes, i'm getting 'This is being overridden by the isSystemOn config setting.'
is there a particular setting that needs to be 'on'?

**Comment by putyourlightson** [comment]
This is a Craft configuration setting. Have a look in the `config/general.php` for the `isSystemOn` attribute. You can either set it to `true` or comment out the line so that you can change this in the control panel.

**Comment by InLoop-TOCA** [comment]
my team is looking into this today.

**Comment by putyourlightson** [comment]
OK, keep us posted.

**Comment by InLoop-TOCA** [comment]
currently systemOn  is set as true, however i am still getting the same error message as the original error from above.

**Comment by putyourlightson** [comment]
Can you please share the URL to the site or email it to info@putyourlightson.net and we’ll take a look.

**Comment by InLoop-TOCA** [comment]
i have sent the URL to info@putyourlightson.net

**Comment by putyourlightson** [comment]
Fixed in v2.0.3.

**Comment by InLoop-TOCA** [comment]
i'm going to work with my team to get Sherlock up to date

**Comment by InLoop-TOCA** [comment]
Hi,
If i hit update in Sherlock, will it affect anything on craft?
i wanted to make sure beforehand to prevent any outages on staging site.

**Comment by putyourlightson** [comment]
It should update without any issues. It’s always good to do these things on a non-live environment first to ensure there are no problems, but I don’t expect anything to arise with a point update.

**Comment by InLoop-TOCA** [comment]
i'll be running an update some time today so i'll give you an update soon.
