### ISSUE TITLE
Cannot run scan - seems to be ignoring environmental variable for Base URL

### ISSUE THREAD

**Issue by TUSAB-web** [putyourlightson/craft-sherlock#30]
### Describe the bug
When selecting “Scan” the following error is received:

> Page Not Found
> 
> Unable to connect to "https://azureinternal.sitename.here/". Please ensure that the site is reachable and that the system is turned on.

It also appears that Sherlock is enabling the security headers on the internal azure URL only as well, not on the public site name defined in the environmental variable.

### To reproduce
The site’s name is set with an environmental variable. When I go to settings/sites in the Craft CP, it is showing the correct Base URL. But Sherlock doesn’t seem to be noticing this.

### Expected behaviour
I expected Sherlock to properly recognize the site name defined by the environmental variable and recognized in the CP’s “settings/sites” section.

### Versions
- Plugin version: 3.1.2 (Free)
- Craft version: 3.6.13 (Pro)

**Comment by bencroker** [comment]
Sherlock should recognise the site URL. What exactly is the site's base URL set to and how is it being determined?

**Comment by TUSAB-web** [comment]
> Sherlock should recognise the site URL. What exactly is the site's base URL set to and how is it being determined?

The site is https://www.usarmyband.com/ and it is set by an environmental variable of SITE_URL. In the CP under the site, it has a checkmark by “this site has its own base URL” and in the blank for the base URL, $SITE_URL is entered. This is a single-site installation.

Also, FYI: I do have a @web alias set, although I’m not calling it from the CP, but I could if you think that would solve this.
`'@web' => craft\helpers\App::env('SITE_URL'),`

<img width="1132" alt="Screen Shot 2021-05-10 at 15 08 23" src="https://user-images.githubusercontent.com/52001038/117711990-c3eef300-b1a1-11eb-9eaf-e9817629ec9f.png">

**Comment by bencroker** [comment]
I just tested locally using an environmental variable and it works fine. My guess is that your web server is not allowing a Guzzle request to be made to its own URL. Does that sound possible?

**Comment by TUSAB-web** [comment]
> I just tested locally using an environmental variable and it works fine. My guess is that your web server is not allowing a Guzzle request to be made to its own URL. Does that sound possible?

So, the site overall is behind a WAF. Because the WAF owner couldn’t configure it properly for Craft CP access, we go through an “internal” Azure URL for CP access, and that’s behind a firewall you need your IP whitelisted for. 

Still, I am  wondering why it returns the error saying it cannot connect to the Azure “internal" URL instead of the official usarmyband.com URL specified in the environmental variables. Maybe it’s failing on the first one and then trying the Azure “internal” URL as a backup? Let me play with it a bit more and see if I can figure anything else out...

From the log, it seems to be getting blocked by the firewall, and it is trying to access the internal URL instead of the official Base URL of the site for some reason.

`2021-05-10 15:55:47 [][1][info] Client error: `GET http://urlchanged.toprotectthe.innocent/` resulted in a `403 Ip Forbidden` response`

**Comment by bencroker** [comment]
Perhaps it is the CP URL that cannot be connected to? Requests are sent to both the front-end and CP URLs.

**Comment by TUSAB-web** [comment]
> Perhaps it is the CP URL that cannot be connected to? Requests are sent to both the front-end and CP URLs.

That must be it. Does it try to connect to the CP URL from an external IP that I could temporarily whitelist for the scan?

**Comment by bencroker** [comment]
The request comes form the server itself, which should have a fixed IP.

**Comment by TUSAB-web** [comment]
> The request comes form the server itself, which should have a fixed IP.

The web app has a bank of “possible” outbound IP addresses it can use. Adding them to the firewall whitelist fixed the problem. Thanks for your time!

**Comment by bencroker** [comment]
Glad to hear it!
