### ISSUE TITLE
Settings page error

### ISSUE THREAD

**Issue by flickerbox-tom** [putyourlightson/craft-sherlock#33]
### Describe the bug
Clicking on the Sherlock icon in /admin/settings throws a twig runtime error.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "/admin/settings"
2. Click on "Sherlock Icon"
3. See error message "Twig Runtime Error – Twig\Error\RuntimeError Variable "id" does not exist."

### Expected behaviour
To see Sherlock settings page

### Screenshots
Screenshot from my local install but I get the same error when on staging at app.servd.host
![Twig Runtime Error – Twig Error RuntimeError 2022-01-11 10-44-00](https://user-images.githubusercontent.com/632978/149002744-a8bc9d22-fb76-455c-8748-1716afa5cde7.png)

### Versions
- Plugin version: 3.1.3 Lite
- Craft version: 3.5.12.1

**Comment by bencroker** [comment]
Thanks for reporting this. Updating to a more recent version of Craft should resolve it for you automatically, but we'll add a fix to make it compatible with older version as well.

**Comment by flickerbox-tom** [comment]
@bencroker Thanks for the quick response. I'll update the Craft version and hopefully that will resolve it.

**Comment by bencroker** [comment]
Great, let me know how it goes.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-sherlock/commit/f021f31736dd320c6518eb15993ffe62627cb686 and released in version 3.1.4.

**Comment by flickerbox-tom** [comment]
Thanks for this. Getting the CraftCMS up to date was going to be a pain.
