### ISSUE TITLE
Unable to connect error

### ISSUE THREAD

**Issue by celexus** [putyourlightson/craft-sherlock#34]
### Question
I'm seeing the following error in sherlock.log: 

` 2022-02-10 14:46:41 [][1][info] Unable to connect to "https://www.mydomain.com/". Please ensure that the site is reachable and that the system is turned on. `
` 2022-02-10 14:46:41 [][1][info] cURL error 6: Could not resolve host: www.www.mydomain.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.www.mydomain.com/ `

### Additional context
I know that it has something to do with the redirect in my .htaccess but I don't know what exactly I need to change to make it work. 

` RewriteCond %{HTTPS} off [OR] `
` RewriteCond %{HTTP_HOST} !^www\. [NC] `
` RewriteCond %{HTTP_HOST} ^(.*)$  [NC] `
` RewriteRule (.*) https://www.%1/$1 [R=301,L] `

My general.php looks like this: 

` 'aliases' => array( `
` '@baseUrl'       => 'https://www.mydomain.com/') `

Can you please point me in the right direction ?

**Comment by bencroker** [comment]
Is your site's base URL correctly set in the site settings and is the system turned on?

<img width="329" alt="Screenshot 2022-02-10 at 13 30 58" src="https://user-images.githubusercontent.com/57572400/153418128-c3afaf81-31c8-4cf7-a744-10b854dfa084.png">

**Comment by celexus** [comment]
The site is definitely on & the bas URL is set like below: 
![Capture](https://user-images.githubusercontent.com/6831255/153431427-a1cca515-083f-4961-9238-6a4df8299cb0.PNG)

**Comment by bencroker** [comment]
And what is that environment variable set to?

**Comment by ademers** [comment]
I just updated to 3.1.4 in local dev and am getting the following error message when attempting to run a scan:
```Not Found: Unable to connect to "https://example.nitro/". Please ensure that the site is reachable and that the system is turned on.```

I'm quite certain that this wasn't an issue previously. I haven't changed any .env or config settings.

**Update**: Just reverted back to 3.1.3 and am getting same error messages. Weird...


![CleanShot 2022-02-10 at 13 29 08](https://user-images.githubusercontent.com/901095/153473068-7f34ce94-21f8-4cba-ae27-b0c41f227cd3.png)

Could it be the Guzzle version?

**Comment by bencroker** [comment]
@ademers this is very likely a routing issue with Nitro, see https://github.com/putyourlightson/craft-sherlock/issues/26#issuecomment-859698496 for reference.

**Comment by ademers** [comment]
@bencroker Thanks! Runs fine in Production, so I'll just leave it at that for now.

**Comment by bencroker** [comment]
Yeah, that's anyway where you want it to work the most!

**Comment by celexus** [comment]
@bencroker - Environment variable is set as follows in .env: 

PRIMARY_SITE_URL=https://mydomain.com/

**Comment by bencroker** [comment]
@celexus in this happening in a local development environment, like it was for @ademers, or on a staging/production server?

**Comment by celexus** [comment]
@bencroker - it's happening in production

**Comment by celexus** [comment]
@bencroker - I'm sorry I made a mistake the environment variable is set to: https://www.mydomain.com - in my previous reply I left off the www - could this be the issue?

**Comment by bencroker** [comment]
In your original message I'm seeing `Could not resolve host: www.www.mydomain.com`, in which the `www.www` is obviously incorrect. Can you double check your base site URLs are correct and check the error message again?

**Comment by celexus** [comment]
I've re-checked the PRIMARY_SITE_URL in my .env again - it's set to: 

`PRIMARY_SITE_URL=https://www.mydomain.com/`

My site settings reference that environment variable 
![Capture](https://user-images.githubusercontent.com/6831255/153825530-78306df5-5f13-4f68-b673-ece8a0738608.PNG)

My .htaccess is set as follows: 
![Capture2](https://user-images.githubusercontent.com/6831255/153826073-cce3172c-a8b5-48d4-856c-f182ae6a90d3.PNG)

And the error I'm getting in sherlock.log is still the same: 
`2022-02-14 10:11:17 [][1][info] Unable to connect to "https://www.mydomain.com/". Please ensure that the site is reachable `
`and that the system is turned on.`
`2022-02-14 10:11:17 [][1][info] cURL error 6: Could not resolve host: www.www.mydomain.com`
`(see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.www.mydomain.com/`

This is happening on my production environment on Craft CMS 3.7.30.1 & Sherlock PLUS v3.1.4

**Comment by bencroker** [comment]
Can you please email the actual domain name to info@putyourlightson.com and I'll ensure that the site is indeed accessible from a public URL?

**Comment by celexus** [comment]
@bencroker  - thanks, have sent it through

**Comment by bencroker** [comment]
So this turns out to be an issue with your `.htaccess` after all, which is redirecting from `http://www.mydomain.com/` to `https://www.www.mydomain.com/`. The following should resolve it, please test thoroughly if using in production.

```
RewriteCond %{HTTPS} off [OR]
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteCond %{HTTP_HOST} ^(.*)$ [NC]
RewriteRule (.*) https://www.mydomain.com/$1 [R=301,L]
```

**Comment by celexus** [comment]
Thank you, Ben
