### ISSUE TITLE
Several tests failing despite being enable/set in settings

### ISSUE THREAD

**Issue by jrrdnx** [putyourlightson/craft-sherlock#35]
Sherlock 4.0.1
Craft 4.0.3
PHP 8.1.5

I just installed Sherlock and ran a few scans. There are 3 tests that currently show as failed even though they're currently accounted for in the settings (please let me know if I don't have these settings correct).

Screenshot of plugin settings captured on local environment:
![Screen Shot 2022-05-26 at 8 19 08 PM](https://user-images.githubusercontent.com/4584671/170604296-fd534ce9-47d7-4126-b9a5-9830d5678df4.png)

Screenshots of Project Config on production to confirm these settings are in place:
![Screen Shot 2022-05-26 at 8 17 02 PM](https://user-images.githubusercontent.com/4584671/170604360-67021c50-2c9a-48c8-ab94-682ae1ce0ffa.png)
![Screen Shot 2022-05-26 at 8 17 09 PM](https://user-images.githubusercontent.com/4584671/170604362-701018e5-b779-4edc-a01f-641b44e276b5.png)

Screenshot of failed tests:
![Screen Shot 2022-05-26 at 8 16 39 PM](https://user-images.githubusercontent.com/4584671/170605017-91dbef58-ad7d-4a23-bb57-1e9efb98d372.png)

I should note that this site is proxied through Cloudflare, but my understanding is that CF does not modify CSP headers from the origin server. If I'm doing something wrong here please let me know!

**Comment by bencroker** [comment]
You'll really need to view the response headers from the server (or Cloudflare) to confirm this, which you can do in the _Network_ tab of your browser's dev tools. My guess is that either your web server is overwriting the header values, or it is a caching issue (try refreshing the cache, if you use one).

**Comment by jrrdnx** [comment]
Confirmed that these headers are in place. I also forgot to note that this particular site is only used for the control panel and lives on a different subdomain, so all front-end requests are 301 redirected to the primary site that does not currently have those headers in place (still working on that).

Also, the Strict-Transport-Security header test is now passing as expected so it's just the Content-Security-Policy and Referrer-Policy tests that are failing now.

**Comment by bencroker** [comment]
The Sherlock test will run on your primary site's domain, which is likely why the tests are failing.

**Comment by jrrdnx** [comment]
10-4, thanks!
