### ISSUE TITLE
Should the restrict CP feature throw 403 errors rather than 503?

### ISSUE THREAD

**Issue by jamesmacwhite** [putyourlightson/craft-sherlock#36]
Not sure what your thoughts are on this, but 503 as an exception code doesn't quite align to the purpose of restricting CP access.

* 503 Service Unavailable - The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request.

* 403 Forbidden - The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.

To me 403 makes more sense as an exception to throw. The 503 error implies the server is unable or not ready to handle the request. That's not really true. The server is able to handle the request, it just doesn't want to, which a 403 error makes more sense.

**Comment by bencroker** [comment]
That's a good point. I was following the convention in Craft of throwing a 503 HTTP error when the system is turned off, but I see how restricted access is somewhat different.

I've changed the error code to `403` in https://github.com/putyourlightson/craft-sherlock/commit/1e3e4068bec2ae69b2bf8d63346ba2cb82919a19, for the next release, thanks!

**Comment by jamesmacwhite** [comment]
Awesome, thank you.

**Comment by bencroker** [comment]
Released in version 4.2.0.
