### ISSUE TITLE
Craft's Ajax queue runner is itself, an unsafe-inline script

### ISSUE THREAD

**Issue by jonnykates** [putyourlightson/craft-sherlock#37]
I'm trying to enforce a CSP on a site but am struggling to whitelist some inline `<script>` executions that are out of my control; not least Craft's own queue runner code which I believe gets instantiated at the bottom of on every site page.

You can see the source code I'm referencing here:
https://github.com/craftcms/cms/blob/develop/src/queue/Queue.php#L585

A CSP will refuse to execute this inline script unless I give it a nonce attribute (which I can't) or allow `unsafe-inline` in my `script-src` policy, which sort of defeats the point.

This obviously isn't really a bug with Sherlock, but it's curious that I don't seem to be able to safely move my CSP from reporting to enforce without breaking seemingly core Craft functionality.

Just wondering if anyone has encountered this before - either with Craft or other third-party plugins - and whether there are any sensible work arounds to somehow whitelist these unavoidable inline script tags.

**Comment by bencroker** [comment]
I too haven't managed to get around this without allowing `unsafe-inline`. This is probably something that would make more sense to bring up at https://github.com/craftcms/cms/discussions
