### ISSUE TITLE
Not found: Unable to connect to https://www.mydomain.com. Please ensure that the site is reachable and that the system is turned on.

### ISSUE THREAD

**Issue by ajaylti** [putyourlightson/craft-sherlock#38]
Hello...

I am newbie to craft cms and sherlock plugin, my other plugins are working fine but only sherlock plugin gives the below error 
Not found: Unable to connect to https://www.mydomain.com. Please ensure that the site is reachable and that the system is turned on.

Not able to troublehshoot this issue, is this network/firewall/certificate related or something else?

any help would be highly appreciated... 

I dont see .htaccess file, where is this located? Is this related to .htaccess file or web config or do I have to change php file? where do I set the base url?

Thanks

**Comment by bencroker** [comment]
> Not found: Unable to connect to https://www.mydomain.com/. Please ensure that the site is reachable and that the system is turned on.

Is the site reachable and the system turned on?

**Comment by ajaylti** [comment]
Hi Ben...

Thanks for the quick response, yes site is on and other links, plugins are working fine, this is deployed on azure cloud and cloudfare is the CDN

**Comment by bencroker** [comment]
Can you share the URL, or if you prefer not to here, send it to info@putyourlightson.com?

**Comment by ajaylti** [comment]
url is - [https://www-systest.mydomain.co.uk/index.php?p=cms/actions/sherlock/scans/run-scan-ajax&siteId=1]

**Comment by bencroker** [comment]
The page at https://www-systest.mydomain.co.uk/ doesn't appear to be generated by Craft, is it?

**Comment by ajaylti** [comment]
no idea Ben.. thats the cms url and plugin uri is as above...what could be the issue?

**Comment by ajaylti** [comment]
craft cms team configured it for us.. we were not involved..

**Comment by bencroker** [comment]
Is the page being generated by Craft? It looks like a parked landing page to me.

<img width="794" alt="Screenshot 2022-10-17 at 09 55 34" src="https://user-images.githubusercontent.com/57572400/196210805-5176cf22-069b-41f2-beb4-d6c5e6d1800d.png">

**Comment by ajaylti** [comment]
aah no I have replaced the domain with mydomain... you will not be able to access the site as it is secured and only whitelisted IP's allowed..

**Comment by bencroker** [comment]
That's what I've been asking this whole time. The plugin needs to be able to access the homepage, so you'll need to whitelist the IP address of your web server, to ensure that it can do so.

**Comment by ajaylti** [comment]
apologies Ben if I have not been clear, yes but we whitelisted lot of IP's still the same issue

**Comment by bencroker** [comment]
Ok, well all I can tell you is that this is the explanation for the error message you're seeing.

**Comment by ajaylti** [comment]
okk thanks Ben, its an appservice in azure, do you think the sherlock request goes out to cloudflare server? or it runs within the domain itself?

**Comment by bencroker** [comment]
It goes out via a HTTP request, so as if from an external client.

**Comment by ajaylti** [comment]
Hi Ben...

Yes I digged the code and could see it forms http scheme.. any reason why it does so, does that mean it should be run on http protocol, my CP is blocking http, what should I do? will editing .htaccess help? any workaround? BTW my craft is PRO and sherlock is lite...

**Comment by bencroker** [comment]
It generates a HTTP(S) request to both your site's front-end and the control panel. Provided the IP address is allowed, it should work.

**Comment by ajaylti** [comment]
Thanks Ben could you please clarify which IP address to allow, because we have given bunch of IP addresses, but no success, my site DNS is set with CP, editing .htaccess will it help?

**Comment by bencroker** [comment]
Specifically, the IP address(es) that HTTP requests will come from the origin web server.
