### ISSUE TITLE
Content Security Policy not being applied to Logged in Admin Users

### ISSUE THREAD

**Issue by creode-dev** [putyourlightson/craft-sherlock#39]
Hi @bencroker ,

I've been looking into a Content Security Policy for my site but have noticed some strange behaviour where it isn't being applied when logged into the site as an admin. Just wondering if this was done by design as during development of a website this feature makes it difficult for us to accurately test issues relating to Content Security Policy.

Thanks

**Comment by bencroker** [comment]
Content Security Policy are not applied when the debug toolbar is enabled on the front-end, since it can results in required resources being blocked. Could that be the issue you're facing?

**Comment by creode-dev** [comment]
Hey @bencroker ,

I think this could be the issue I am facing yes. I'm guessing that it is also disabled in admin panel as Craft requires 'unsafe-inline' scripts in order to function correctly?

Thanks

**Comment by bencroker** [comment]
Correct, as per the docs at https://putyourlightson.com/plugins/sherlock#content-security-policy

> Enables a content security policy on the front-end of your site.
