### ISSUE TITLE
Failed Scan 

### ISSUE THREAD

**Issue by hegrobler** [putyourlightson/craft-sherlock#4]
I'm using Sherlock v1.3.4 on a Craft site running v2.7.4

Below is a screenshot of the Sherlock scan: 
![sherlock-scan](https://user-images.githubusercontent.com/354816/52258828-34569c00-2929-11e9-98bc-e8da9ae8785d.PNG)

The plugin indicates that the site failed the security scan. 
Below is a screenshot of the headers as seen in my network tab: 
![headers](https://user-images.githubusercontent.com/354816/52258848-45071200-2929-11e9-96be-4d2f397b1202.PNG)

The site is definitely running on HTTPS & the headers seem to be correct. 

Why would Sherlock indicate that the site fails the security scan ? 

Would appreciate any information or assistance you can provide.

**Comment by putyourlightson** [comment]
Can you please double check that the site you are testing is publicly accessible? Sherlock will not be able to run its full set of tests unless it is. If it is, then please send the URL to info@putyourlightson.net and we'll take a closer look.

**Comment by putyourlightson** [comment]
This issue is being addressed through email support, closing.
