### ISSUE TITLE
Some security scan tests come back as a warning when using a page cached with Blitz plugin

### ISSUE THREAD

**Issue by icreatestuff** [putyourlightson/craft-sherlock#44]
We recently ran a security scan on a website using the Blitz caching plugin.

We noticed that if we clear the caches before running the scan, every test passes. However, if we run the scan when a majority of the site has cached pages the following tests related to headers come back as warnings.

![Screenshot 2023-12-13 at 10 59 46](https://github.com/putyourlightson/craft-sherlock/assets/1300714/39fe4225-a28b-4b62-82f5-a3a6fa462d80)

When we inspect the request in the developer tools Network tab we can also see the headers visible when a page is uncached, and missing when a page is cached.

We have the following rules setup in our htaccess file related to Blitz.

```apacheconf
# Blitz cache rewrite for gzip files
RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html.gz -s
RewriteCond %{HTTP:Accept-encoding} gzip
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !token= [NC]
RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html.gz [L]

# AddEncoding allows you to have certain browsers uncompress information on the fly.
AddEncoding gzip .gz

# Serve correct content types, and prevent mod_deflate double gzip.
RewriteRule \.html\.gz$ - [T=text/html,E=no-gzip:1]

# Blitz static cache rewrite
RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html -s
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !token= [NC]
RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html [L]
```

Could this be a configuration setting we have wrong in blitz/htaccess, or a bug in one of the plugins?

Many thanks

**Comment by bencroker** [comment]
Since you’re using Blitz server rewrites, requests to cached pages will not reach Craft, which is likely where these headers are being set. 

To get around this, you‘ll need to set those headers in your `.htaccess` file (or Apache configuration file). See more details on how to do this at https://developer.mozilla.org/en-US/docs/Learn/Server-side/Apache_Configuration_htaccess

**Comment by icreatestuff** [comment]
Understood. We'll set up the equivalent headers at the server level and presumably remove them from the Sherlock settings so they aren't doubled up? Thanks for the link.

**Comment by bencroker** [comment]
Yeah I think that makes sense, needs testing though.
