### ISSUE TITLE
Installed this and it wiped my project.yaml :(

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#5]
I installed the plugin via composer. 

When I activated it I immediately got the following:

![image](https://user-images.githubusercontent.com/7523595/58812551-07d23880-861a-11e9-947a-687102bf7863.png)

And then found my `project.yaml` is now empty :(

Any ideas where I can start trying to debug this?

**Comment by putyourlightson** [comment]
Firstly, you should be able to restore the `project.yaml` file from the most recent backup in `storage/config-backups`.

I don't think this issue is related to Sherlock though. What version of Craft are you running? The earlier 3.1.x versions had some issues but most if not all have been resolved by now (currently 3.1.28).

**Comment by sunscreem** [comment]
Thanks Ben, Did a config/rebuild and sorted that no problem. All updates done, 3.1.28, commerce 2, etc.

There's quite a lot of plugs in on this site, 20+. 

I've not had any problems like this with other plug ins, so I'm guessing there is some combination of sherlock and something else that's causing the issue.

Not sure where to begin debugging it aside from turning off all the plugins and re-adding them.

Anything in the screen grab jump out at you that might point me in the right direction?

**Comment by putyourlightson** [comment]
Are you able to install locally or on a staging server to see if the same happens there? I tested it locally and am not experiencing this issue.

**Comment by sunscreem** [comment]
Yeah - Running this locally. I'm guessing it's some weird combination of our plugins and project.yaml. I'll do some testing and re-open this if I can't get anywhere. Thanks @putyourlightson

**Comment by putyourlightson** [comment]
Ok sounds good.

**Comment by sunscreem** [comment]
Hey @putyourlightson FYI - disabled all plugins, installed sherlock, enabled all plugs in and can finally start the trial :)

**Comment by putyourlightson** [comment]
Glad to hear it!
