### ISSUE TITLE
Default Token Duration Issue

### ISSUE THREAD

**Issue by sunscreem** [putyourlightson/craft-sherlock#8]
Hi,

Not sure if this is related to #6 but I've now got this:

![image](https://user-images.githubusercontent.com/7523595/59552640-941d1d80-8f81-11e9-86d8-4249c2825327.png)

In my config I have:

```
 'defaultTokenDuration'            => 82800, // 23 hours
```

**Comment by putyourlightson** [comment]
Thanks, looks like that setting did not get corrected, we'll release a fix shortly.

**Comment by putyourlightson** [comment]
Fixed in version 2.1.2.
