### ISSUE TITLE
Internal Server Error While running Sherloack Security Plugin

### ISSUE THREAD

**Issue by mrudhulcgvak** [putyourlightson/craft-sherlock#9]
Hi Team,

I am getting below error when running Sherlock plugin
Internal Server Error

get_headers(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0
![image](https://user-images.githubusercontent.com/11275316/62053563-8243c100-b235-11e9-9ebd-81e2b57618eb.png)

:

**Comment by putyourlightson** [comment]
Enabling `allow_url_fopen` is one of Craft's requirements for updating and installing plugins from the Plugin Store (https://docs.craftcms.com/v3/requirements.html#optional-php-methods-and-configurations) so you should really enable it if possible. A web search should yield plenty of results on how to.
